# @name Get all persons
GET http://localhost:3001/api/persons
Accept: application/json

### Create a person Sebastian
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Sebastian",
  "number": "30120121221"
}

### Create a person Arto
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "30120121221"
}

###
